### ISSUE TITLE
More future

### ISSUE THREAD

**Issue by shikulja** [john32b/cdcrush.net#10]
add 7z
because for example retroarh, it allows you to open 7z on the fly, without arms (removal / unpacking)

Several images in one archive
This is very effective if there are several little different images - translations, hacks.
In this case, solid archive 7z, lrzip is used.

**Comment by john32b** [comment]
It's been a while since I followed any retroarch news. Does it mount the archive with random access or extracts it to memory or something? If it's a real mount then that's great! ( I can't find any documentation for it )

I was thinking on replacing freearc with 7zip a while back #2 
If this is the case then I will add this, as it seems really useful to have playable .7z cd images!

**Comment by john32b** [comment]
Testing things out and loading some 7z games with retroarch. 
It appears to be working, had problems with some games not loading at all.
What are the optimal/compatible compression settings? It appears that it has to be low compression else it takes forever for it to load, (if it ever loads!)

**Comment by shikulja** [comment]
> Testing things out and loading some 7z games with retroarch.
> It appears to be working, had problems with some games not loading at all.
> What are the optimal/compatible compression settings? It appears that it has to be low compression else it takes forever for it to load, (if it ever loads!)

lzma (1), 1024mb, ultra. No folders, subfolders in 7z, bin + cue 
ecw+cue, ecw + tracs + cue - not read (its my error) (need fix retroarh)
Startup speed depends on ssd and computer power (extracting the archive).
on my 7700k,32Gb mem, ssd sata the speed is quite fast

He seems to be extracting the file temporarily from the archives on disk

if the archive Browse, therefore, it can only open single images, iso bin.
If load 7z, then the first image is read by name+single bin

a little crooked work, but so no bad
I think over time they will fix his work, but obviously not soon, as I read they have no desire to add different formats

also m3u seems to be reading too, but need fix

**Comment by john32b** [comment]
Added 7zip in V1.5 release 0845354e795cc38e0c1e6a40576850666e113781
- Can create `.7z` and `.zip` archives with some predefined compression settings
- 7zip can be used for both normal backups and creating `.cue` with encoded audio tracks
