### ISSUE TITLE
Request: Opus Codec

### ISSUE THREAD

**Issue by RollingStar** [john32b/cdcrush.net#5]
Opus is a modern audio codec with better compression at the same apparent audio quality. 96kbps fared well in HydrogenAudio (audio enthusiast community) tests. 

https://www.opus-codec.org/

It's built into ffmpeg as well.

**Comment by john32b** [comment]
Hm, I hadn't researched Opus that much and it seems promising. I might as well replace the default libvorbis method with opus if it does indeed offer better results!

**Comment by john32b** [comment]
V1.2.2 now uses the OPUS codec with some predefined quality bitrates
