### ISSUE TITLE
Set default ffmpeg path to the tools directory upon downloading and first run of the program

### ISSUE THREAD

**Issue by dubbz82** [john32b/cdcrush.net#8]
Since FFMpeg is included with the program (at least with the full copy of it) the default path of ffmpeg.exe should match the folder where the file is put by default.  This may make it a little easier for end-users that aren't savvy enough to know where the executable is dropped and will make the program immediately usable right out out of the gates for users who download the full version.

**Comment by john32b** [comment]
Hello,
You are right! I completely missed this.
On the full version the ffmpeg path should point to the `tools` folder. 
I'll make an update soon 😄 
Cheers

**Comment by john32b** [comment]
Thanks for the bug report. I'll update the binaries sometime tomorrow
